### ISSUE TITLE
Incompatibility with Webpack 5

### ISSUE THREAD

**Issue by GorvGoyl** [tettusud/merge-jsons-webpack-plugin#64]
I'm not able to run webpack in `development` mode when `source-map` is enabled and set to `cheap-module-source-map` or `inline-source-map`.
On digging I found out your plugin is not fully compatible with webpack v5 which is causing that issue.
To test:
`node --trace-deprecation node_modules/webpack/bin/webpack.js`
Output:
```
(node:14444) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at MergeJsonWebpackPlugin.addAssets (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\merge-jsons-webpack-plugin\index.js:234:42)
    at C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\merge-jsons-webpack-plugin\index.js:38:30
    at tryCatch (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:195:12)   
    at invokeCallback (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:210:13)
    at publish (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:178:7)     
    at flush (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\es6-promise\dist\lib\es6-promise\asap.js:98:5)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

You can see that webpack config file: https://github.com/GorvGoyl/Notion-Boost-browser-extension/blob/72c0da7202b2cbcd6006d553fe59035abdb8d9e4/webpack.config.js#L217

**steps to reproduce:**

Clone https://github.com/GorvGoyl/Notion-Boost-browser-extension/tree/webpack5_devtool_bug
npm install
run webpack in development mode npm run start:ch
build would fail with above error.
What is the expected behavior?

Other relevant information:
webpack version: 5.6.0
Node.js version: 12.15.0
Operating System: Win10
Additional tools: Powershell Core, VSCode

I previously filed this bug for Webpack https://github.com/webpack/webpack/issues/12041

**Comment by tettusud** [comment]
@GorvGoyl I cant see the git repo, and also I tested with the below webpack version and I do not see any errors, could you help me with a sample, please?
```
 "webpack": "^5.11.0",
  "webpack-dev-server": "^3.11.0"
```

**Comment by aarthishuba** [comment]
@GorvGoyl published new version 2.0.0-alpha, however it has some breaking changes in case of array behaviour, you can check read me file

**Comment by pilpo** [comment]
Even with the new version 2.0.0-alpha, I still get the error on my project. It's not a big deal so far :)

**Comment by ybentz** [comment]
Hey! Any updates on this?
I found a couple of related issues on `html-webpack-plugin` that were fixed already in case that helps.
- [issue 1](https://github.com/jantimon/html-webpack-plugin/issues/1501)
- [issue 2](https://github.com/jantimon/html-webpack-plugin/issues/1523)
